enum RouteNames {
	//public
	LOGIN = 'LOGIN',
	REGISTER = 'REGISTER',
	VERIFY_EMAIL = 'VERIFY_EMAIL',
	FORGOT_PASSWORD = 'FORGOT_PASSWORD',
	RESET_PASSWORD = 'RESET_PASSWORD',

	//secured
	DASHBOARD = 'DASHBOARD',
	MANAGEMENT_WALLETS = 'MANAGEMENT_WALLETS',
	CREATE_WALLETS = 'CREATE_WALLETS',
	EDIT_WALLETS = 'EDIT_WALLETS',
	MANAGEMENT_CATEGORY = 'MANAGEMENT_CATEGORY',
	CREATE_CATEGORY = 'CREATE_CATEGORY',
	EDIT_CATEGORY = 'EDIT_CATEGORY',
	NOTES = 'NOTES',
	CREATE_NOTE = 'CREATE_NOTE',
	DETAIL_NOTE = 'DETAIL_NOTE',
	NOTE_ITEMS = 'NOTE_ITEMS',
	CREATE_NOTE_ITEMS = 'CREATE_NOTE_ITEMS',
	EDIT_NOTE_ITEMS = 'EDIT_NOTE_ITEMS',
	MY_PROFILE = 'MY_PROFILE',
	CHANGE_PASSWORD = 'CHANGE_PASSWORD',
	ABOUT_US = 'ABOUT_US',
}

export default RouteNames;
